function atualizar(){
    var container_1 = document.getElementsByClassName("container-1")
    var propaganda_principal_footer = document.getElementsByClassName("propaganda-principal-footer")
    var propaganda_monitores = document.getElementsByClassName("propaganda-monitores")
    let data = new Date()
    let segundos = data.getSeconds()
    if(segundos<5){
        container_1[1].style.display='none'
        container_1[0].style.display='flex'
        container_1[2].style.display='none'
        container_1[3].style.display='flex'
        container_1[4].style.display='none'
        container_1[5].style.display='flex'
        container_1[6].style.display='none'
        container_1[7].style.display='flex'
        container_1[8].style.display='none'
        container_1[9].style.display='flex'
        container_1[10].style.display='none'
        container_1[11].style.display='flex'
    }else if(segundos<10){
        container_1[0].style.display='none'
        container_1[1].style.display='flex'
        container_1[3].style.display='none'
        container_1[2].style.display='flex'
        container_1[5].style.display='none'
        container_1[4].style.display='flex'
        container_1[7].style.display='none'
        container_1[6].style.display='flex'
        container_1[9].style.display='none'
        container_1[8].style.display='flex'
        container_1[11].style.display='none'
        container_1[10].style.display='flex'

        propaganda_principal_footer[0].style.display='none'
        propaganda_monitores[0].style.display='flex'
        
    }else if(segundos<15){
        container_1[1].style.display='none'
        container_1[0].style.display='flex'
        container_1[2].style.display='none'
        container_1[3].style.display='flex'
        container_1[4].style.display='none'
        container_1[5].style.display='flex'
        container_1[6].style.display='none'
        container_1[7].style.display='flex'
        container_1[8].style.display='none'
        container_1[9].style.display='flex'
        container_1[10].style.display='none'
        container_1[11].style.display='flex'
        
    }else if(segundos<20){
        container_1[0].style.display='none'
        container_1[1].style.display='flex'
        container_1[3].style.display='none'
        container_1[2].style.display='flex'
        container_1[5].style.display='none'
        container_1[4].style.display='flex'
        container_1[7].style.display='none'
        container_1[6].style.display='flex'
        container_1[9].style.display='none'
        container_1[8].style.display='flex'
        container_1[11].style.display='none'
        container_1[10].style.display='flex'
        propaganda_monitores[0].style.display='none'
        propaganda_principal_footer[0].style.display='flex'
        
        
    }else if(segundos<25){
        container_1[1].style.display='none'
        container_1[0].style.display='flex'
        container_1[2].style.display='none'
        container_1[3].style.display='flex'
        container_1[4].style.display='none'
        container_1[5].style.display='flex'
        container_1[6].style.display='none'
        container_1[7].style.display='flex'
        container_1[8].style.display='none'
        container_1[9].style.display='flex'
        container_1[10].style.display='none'
        container_1[11].style.display='flex'
        
    }else if(segundos<30){
        container_1[0].style.display='none'
        container_1[1].style.display='flex'
        container_1[3].style.display='none'
        container_1[2].style.display='flex'
        container_1[5].style.display='none'
        container_1[4].style.display='flex'
        container_1[7].style.display='none'
        container_1[6].style.display='flex'
        container_1[9].style.display='none'
        container_1[8].style.display='flex'
        container_1[11].style.display='none'
        container_1[10].style.display='flex'
        propaganda_principal_footer[0].style.display='none'
        propaganda_monitores[0].style.display='flex'
        
    }else if(segundos<35){
        container_1[1].style.display='none'
        container_1[0].style.display='flex'
        container_1[2].style.display='none'
        container_1[3].style.display='flex'
        container_1[4].style.display='none'
        container_1[5].style.display='flex'
        container_1[6].style.display='none'
        container_1[7].style.display='flex'
        container_1[8].style.display='none'
        container_1[9].style.display='flex'
        container_1[10].style.display='none'
        container_1[11].style.display='flex'
        
    }else if(segundos<40){
        container_1[0].style.display='none'
        container_1[1].style.display='flex'
        container_1[3].style.display='none'
        container_1[2].style.display='flex'
        container_1[5].style.display='none'
        container_1[4].style.display='flex'
        container_1[7].style.display='none'
        container_1[6].style.display='flex'
        container_1[9].style.display='none'
        container_1[8].style.display='flex'
        container_1[11].style.display='none'
        container_1[10].style.display='flex'
        propaganda_monitores[0].style.display='none'
        propaganda_principal_footer[0].style.display='flex'
        
    }else if(segundos<45){
        container_1[1].style.display='none'
        container_1[0].style.display='flex'
        container_1[2].style.display='none'
        container_1[3].style.display='flex'
        container_1[4].style.display='none'
        container_1[5].style.display='flex'
        container_1[6].style.display='none'
        container_1[7].style.display='flex'
        container_1[8].style.display='none'
        container_1[9].style.display='flex'
        container_1[10].style.display='none'
        container_1[11].style.display='flex'
        
    }else if(segundos<50){
        container_1[0].style.display='none'
        container_1[1].style.display='flex'
        container_1[3].style.display='none'
        container_1[2].style.display='flex'
        container_1[5].style.display='none'
        container_1[4].style.display='flex'
        container_1[7].style.display='none'
        container_1[6].style.display='flex'
        container_1[9].style.display='none'
        container_1[8].style.display='flex'
        container_1[11].style.display='none'
        container_1[10].style.display='flex'
        propaganda_principal_footer[0].style.display='none'
        propaganda_monitores[0].style.display='flex'
        
    }else if(segundos<55){
        container_1[1].style.display='none'
        container_1[0].style.display='flex'
        container_1[2].style.display='none'
        container_1[3].style.display='flex'
        container_1[4].style.display='none'
        container_1[5].style.display='flex'
        container_1[6].style.display='none'
        container_1[7].style.display='flex'
        container_1[8].style.display='none'
        container_1[9].style.display='flex'
        container_1[10].style.display='none'
        container_1[11].style.display='flex'
        
    }else if(segundos<60){
        container_1[0].style.display='none'
        container_1[1].style.display='flex'
        container_1[3].style.display='none'
        container_1[2].style.display='flex'
        container_1[5].style.display='none'
        container_1[4].style.display='flex'
        container_1[7].style.display='none'
        container_1[6].style.display='flex'
        container_1[9].style.display='none'
        container_1[8].style.display='flex'
        container_1[11].style.display='none'
        container_1[10].style.display='flex'
        propaganda_monitores[0].style.display='none'
        propaganda_principal_footer[0].style.display='flex'
    }
}

setInterval(atualizar, 200)